# This workflow will launch at 00:00 every Sunday
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 1,11,21 * *'

name: Launch Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.REPO_GITHUB_TOKEN }}
          author-email: 12345+octocat@users.noreply.github.com
          author-name: "Scala Steward on GitHub Actions"
