on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

name: Launch Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          author-email: gerdreiss-steward[bot]@users.noreply.github.com
          author-name: gerdreiss-steward[bot]
